sudo: true
dist: trusty
language: python
matrix:
  include:
    - python: "3.5"
before_install:
    - "pip install 'lander>=0.1.0,<0.2'"
script:
# Compile PDF using containerized lsst-texmf
    - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
# Deploy website. See https://github.com/lsst-sqre/lander for CLI options
    - "lander --pdf ${PRODUCT}.pdf --upload --lsstdoc ${PRODUCT}.tex --env=travis --ltd-product $PRODUCT --title \"$TITLE\" --abstract \"$ABSTRACT\" --docushare-url $DOCUSHAREURL"
env:
global:
   - PRODUCT="LDM-294"
# Manually managed metadata that Lander current can't parse from tex
   - ABSTRACT="Managemnt and orgnaizaiton of Data Management"
   - TITLE="Data Management Management Plan"
   - DOCUSHAREURL="https://ls.st/ldm-294*"
# Add LSST the Docs credentials
    - secure: "fqSjpqeC4Els8A4eKk0IXSGPvtSrLVMG0Z31b7UrwdTMOQRUJrLkka7fIxqaQCgRkNiLa1zDdtfQEaO/peuB4hbhI5l1uvL0WBCMYEetvVyDJOZy5gF2+gk4yT+67pUzbidVc/tybpV21qOeHjVR32S3S0KzuCQtafmd1d1W51Rr0ektNsyM9fFdq9wI8EECvPuArkHShYYVqp8lysJNoOywGKxbCYusk6XZbwYNBODEDmEosv9TtonqUfXJg2gIDo+QN9bQut1bWJgwPXB8bY1fhnNexUbMfnnkF/VwiYOdj+0S5YJdH1ne7oYfbLzKXGQllQDy8xp05pArjMr2O8pTZ4dCU6E+izK4NGBXh6dFS+rg53jKygJx/NbBsunpdzVSPnUYrv80WnAnd0I7rtBMcvW4sk76ezgaLcpzzkbEz+w1aLKnORRUTMKxrW0ccQF1zBRR2/MT2BgD2XdBTY8QuxZKj14HwXVIYnPnWowy4TwaSrafVQNNYDPIoj7TqmuokL5qlJi8iEQfNtKL8eUJzFdaVHNmeCCdg9Fck2zf5B0Vxzv+waWwStXZ0UxpGjrIrxkoHwY76rAhkDREoE/tJeCTwXHD0e+5aSObgnt+O0XVwBzS4qA4mdRsuLi/+oq5VqIhv767sLvh2Rdb/D3BNfU0jB7TctGlIcPVFno="
    - secure: "DpHxUeTW5V6CJzckyvYFPctFd8Rpe9v+2Y/BHZwH79P5z3RM5C8FGLfeOC7buAPvLN9WOrMDaHylZKkcS4Q27F86tf7sELZj06QLM5oq+z+HtS0XoOFyBnzFGgXIphBkfB5bBEO4Tkc25/z58Cf2/eRppcm7ajqgQEgVRcTz/FN8Ut5uoUUbOs4h7G3RmUf2Andn8Mqua6tfC04hBn2y5kPEVN4hDch3h7TaRGA0HXf5xLzzblOPfMX+pKqLYcmEUMfyjXwbWtzQgmW4rVvNeB4r74IGHef7aS/Jy7U2lufKKM6kRS44zcrWzmOPlstBWlKScr11LEMG8sg302EtjDR5QxNoBC8YTqZuoyko7WQqb7uinTgDw3CSU4MKuJNPelC+Ke5VVOF0U1fve9hQjFGW86gc/chM1jnXDtZk48pnvn2jRlMRhOUW/ufL2pocJx9J5tin4azZ4JK0KtDCE39d8cpjATZY3FZNrYDck7F6mmIfUEv9a5Y67kpVrlEx8a77nthZqyxr5gL1Whf7MheXAzhkEW6olnoLTIZ7HcIc4SXkjnqjAGwYlbOllkgXQu8rFWKz6sr6xVzuwLA8GIbRCIgISGwhJbX3mHApAbaea50UsGSiQ1HSLhPDFa7XrgEDQvp2G4ONDPZsp5fzEKf1ZdZx+XfY9PLXIMcqeF4="
